version: "3"
services:
  bar:
    image: bar
    restart: on-failure
    ports:
    - "8080:8080"
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    restart: always
    ports:
    - "3305:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=bar
    volumes:
    - /opt/mysql/data:/var/lib/mysql