version: "3"
services:
  bar:
    image: rizhiy04/bar
    restart: on-failure
    ports:
    - "8080:8080"
    depends_on:
      - mysqldb
      - jenkins

  mysqldb:
    image: mysql:8
    restart: always
    ports:
    - "3305:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=bar
    volumes:
    - /opt/mysql/data:/var/lib/mysql

  jenkins:
    image: rizhiy04/jenkins-jdk11-docker
    ports:
    - "8081:8080"
    restart: on-failure
    volumes:
    - /opt/jenkins_home:/var/jenkins_home